// Generated by CoffeeScript 1.3.1
(function() {
  var fs, r;

  fs = require('fs');

  r = {
    load: function(file, callback) {
      return fs.readFile(file, 'utf8', function(err, data) {
        if (!err) {
          data = data.replace(/\@import/ig, '');
        }
        return callback(data);
      });
    }
  };

  module.exports = r;

}).call(this);
